# Generated by Django 4.1 on 2023-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0002_rename_users_appusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="appusers",
            name="login",
            field=models.CharField(default="login", max_length=200),
        ),
    ]
