# Generated by Django 4.1 on 2023-05-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0003_appusers_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appusers",
            old_name="passowrd",
            new_name="password",
        ),
    ]
