# Generated by Django 4.1 on 2023-05-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0004_rename_passowrd_appusers_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appusers",
            name="login",
            field=models.CharField(default="login", max_length=200, unique=True),
        ),
    ]
