# Generated by Django 4.2.1 on 2023-05-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0007_myuser"),
    ]

    operations = [
        migrations.DeleteModel(name="MyUser",),
    ]
