# Generated by Django 4.1 on 2023-05-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0008_delete_myuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appusers",
            name="id",
        ),
        migrations.AddField(
            model_name="appusers",
            name="ID_Uzytkownika",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
