# Generated by Django 4.1 on 2023-05-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0010_zgloszenie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appusers",
            name="ID_Uzytkownika",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
