# Generated by Django 4.1 on 2023-05-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0011_alter_appusers_id_uzytkownika"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zgloszenie",
            name="x",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="zgloszenie",
            name="y",
            field=models.FloatField(),
        ),
    ]
