# Generated by Django 4.1 on 2023-05-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0012_alter_zgloszenie_x_alter_zgloszenie_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgloszenie",
            name="typ_zgloszenia",
            field=models.IntegerField(default=0),
        ),
    ]
