# Generated by Django 4.1 on 2023-05-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0015_alter_zgloszenie_id_uzytkownika"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zgloszenie",
            name="Czas_zgloszenia",
            field=models.DateField(auto_now_add=True),
        ),
    ]
