# Generated by Django 4.2.1 on 2023-05-23 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_alter_zgloszenie_id_uzytkownika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenie',
            name='Czas_zgloszenia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
