# Generated by Django 4.2.1 on 2023-05-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0018_alter_zgloszenie_czas_zgloszenia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zgloszenie',
            old_name='Czas_zgloszenia',
            new_name='czas_dodania',
        ),
    ]
